# Generated by Django 5.1.5 on 2025-12-03 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0002_remove_task_answer_remove_task_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="text_question",
        ),
    ]
